### PR TITLE
Fix file saving and loading on macOS

### PR DESCRIPTION
**Pull request by matt-aaron**
This fixes the functionality to work with files on macOS. I tested this after building with Qt 5.14.1.

### CODE REVIEW

**Comment by altlenny** [comment]
Hey msaaron,

thank your for that fix. Much appreciated! I'm sorry for my inactivity and that I haven't revisited this repo until today.

Could you please also update the mac-deployment zip in the bin folder? After that I'm happy to merge the pull request :)

Best,
Stephan

**Comment by ForceVectorDestroy** [comment]
Hi, I see msaaron made a fix for the MacOS file saving and loading but I have no idea how to program or use code. How do I take his fix and make FVD++ usable on MacOS?

There is also a small problem of some tabs not showing text on MacOS. For example, at the top left of the project window the "project/unnamed track" tabs will only show text on the tab you have selected and the other remains blank. 

I would really like to get FVD++ working correctly on MacOS. FVD++ is such a valuable tool for this community!

**Review by ForceVectorDestroy — COMMENTED** [review]
Hi, I'm a complete novice to code so how do I apply these changes to make the MacOS version able to save and load files?

**Comment by geforcefan** [comment]
Gonna check this pull request, afaik the are not compiled, need to compile them and add those into the code base

**Comment by ForceVectorDestroy** [comment]
Thanks, geforcefan. I'm new to github so not sure exactly how to use this site. Sorry for the double post regarding the MacOS problem.

**Comment by geforcefan** [comment]
Resolved in the new "version", binaries are updated, closing this issue...

**Pull request closed without merging**
